global:
  account: '649999766497'
  region: 'us-east-1'
  common_prefix: 'dom-ai'
  env: 'poc'
  tags:
    owner: 'EPWERY'
    project: 'Domesticated AI PoC'
    env: 'poc'
    contact: 'lmv.vidal@gmail.com'

networking:
  vpc_cidr: '172.32.0.0/16'
  az_count: 2
  public_subnet_name: 'PublicSubnet'
  public_subnet_prefix: 20
  private_subnet_name: 'PrivateSubnet'
  private_subnet_prefix: 20
  isolated_subnet_name: 'IsolatedSubnet'
  isolated_subnet_prefix: 20

security:
  pgres_port: 5432
  cf_prefix_list: 'pl-3b927c52'

compute:
  ec2_be_machine_type: 't2.micro'
  ebs_device_name: '/dev/xvda'

database:
  database_name: 'epwery'

ui:
  # no values yet

access:
  pgres_port: 5432
  cache_policy_be: 'disabled'
  cache_policy_ui: 'enabled'
